class PickupDate < ActiveHash::Base
  self.data = [
    { id: 1, from: '北海道', to: '北海道', days: 1 }, { id: 2, from: '北海道', to: '東北', days: 2 },
    { id: 3, from: '北海道', to: '関東', days: 2 }, { id: 4, from: '北海道', to: '甲信越', days: 2 },
    { id: 5, from: '北海道', to: '北陸', days: 3 }, { id: 6, from: '北海道', to: '東海', days: 3 },
    { id: 7, from: '北海道', to: '近畿', days: 3 }, { id: 8, from: '北海道', to: '四国', days: 3 },
    { id: 9, from: '北海道', to: '中国', days: 3 }, { id: 10, from: '北海道', to: '九州', days: 3 },
    { id: 11, from: '北海道', to: '沖縄', days: 3 },
    { id: 12, from: '東北', to: '北海道', days: 2 },{ id: 13, from: '東北', to: '東北', days: 1 }, 
    { id: 14, from: '東北', to: '関東', days: 1 },{ id: 15, from: '東北', to: '甲信越', days: 2 }, 
    { id: 16, from: '東北', to: '北陸', days: 2 },{ id: 17, from: '東北', to: '東海', days: 2 },
    { id: 18, from: '東北', to: '近畿', days: 2 },{ id: 19, from: '東北', to: '中国', days: 2 }, 
    { id: 20, from: '東北', to: '四国', days: 2 },{ id: 21, from: '東北', to: '九州', days: 3 }, 
    { id: 22, from: '東北', to: '沖縄', days: 3 },
    { id: 23, from: '関東', to: '北海道', days: 2 }, { id: 24, from: '関東', to: '東北', days: 1 },
    { id: 25, from: '関東', to: '関東', days: 1 }, { id: 26, from: '関東', to: '甲信越', days: 1 },
    { id: 27, from: '関東', to: '北陸', days: 1 }, { id: 28, from: '関東', to: '東海', days: 1 },
    { id: 29, from: '関東', to: '近畿', days: 1 }, { id: 30, from: '関東', to: '中国', days: 2 },
    { id: 31, from: '関東', to: '四国', days: 2 }, { id: 32, from: '関東', to: '九州', days: 2 },
    { id: 33, from: '関東', to: '沖縄', days: 3 }, 
    { id: 34, from: '甲信越', to: '北海道', days: 2 },{ id: 35, from: '甲信越', to: '東北', days: 1 },
    { id: 36, from: '甲信越', to: '関東', days: 1 },{ id: 37, from: '甲信越', to: '甲信越', days: 1 },
    { id: 38, from: '甲信越', to: '北陸', days: 1 },{ id: 39, from: '甲信越', to: '東海', days: 1 }, 
    { id: 40, from: '甲信越', to: '近畿', days: 1 },{ id: 41, from: '甲信越', to: '中国', days: 2 }, 
    { id: 42, from: '甲信越', to: '四国', days: 2 },{ id: 43, from: '甲信越', to: '九州', days: 2 }, 
    { id: 44, from: '甲信越', to: '沖縄', days: 3 },
    { id: 45, from: '関東', to: '沖縄', days: 3 }, 
    { id: 46, from: '北陸', to: '北海道', days: 3 },{ id: 47, from: '北陸', to: '東北', days: 2 },
    { id: 48, from: '北陸', to: '関東', days: 1 },{ id: 49, from: '北陸', to: '甲信越', days: 1 },
    { id: 50, from: '北陸', to: '北陸', days: 1 },{ id: 51, from: '北陸', to: '東海', days: 1 }, 
    { id: 52, from: '北陸', to: '近畿', days: 1 },{ id: 53, from: '北陸', to: '中国', days: 2 }, 
    { id: 54, from: '北陸', to: '四国', days: 2 },{ id: 55, from: '北陸', to: '九州', days: 2 }, 
    { id: 56, from: '北陸', to: '沖縄', days: 3 },
    { id: 57, from: '東海', to: '北海道', days: 3 },{ id: 58, from: '東海', to: '東北', days: 2 },
    { id: 59, from: '東海', to: '関東', days: 1 },{ id: 60, from: '東海', to: '甲信越', days: 1 },
    { id: 61, from: '東海', to: '北陸', days: 1 },{ id: 62, from: '東海', to: '東海', days: 1 }, 
    { id: 63, from: '東海', to: '近畿', days: 1 },{ id: 64, from: '東海', to: '中国', days: 2 }, 
    { id: 65, from: '東海', to: '四国', days: 2 },{ id: 66, from: '東海', to: '九州', days: 2 }, 
    { id: 67, from: '東海', to: '沖縄', days: 3 },
    { id: 68, from: '近畿', to: '北海道', days: 3 },{ id: 69, from: '近畿', to: '東北', days: 2 },
    { id: 70, from: '近畿', to: '関東', days: 1 },{ id: 71, from: '近畿', to: '甲信越', days: 1 },
    { id: 72, from: '近畿', to: '北陸', days: 1 },{ id: 73, from: '近畿', to: '東海', days: 1 }, 
    { id: 74, from: '近畿', to: '近畿', days: 1 },{ id: 75, from: '近畿', to: '中国', days: 1 }, 
    { id: 76, from: '近畿', to: '四国', days: 1 },{ id: 77, from: '近畿', to: '九州', days: 2 }, 
    { id: 78, from: '近畿', to: '沖縄', days: 3 },
    { id: 79, from: '中国', to: '北海道', days: 3 },{ id: 80, from: '中国', to: '東北', days: 2 },
    { id: 81, from: '中国', to: '関東', days: 2 },{ id: 82, from: '中国', to: '甲信越', days: 2 },
    { id: 83, from: '中国', to: '北陸', days: 2 },{ id: 84, from: '中国', to: '東海', days: 2 }, 
    { id: 85, from: '中国', to: '近畿', days: 1 },{ id: 86, from: '中国', to: '中国', days: 1 }, 
    { id: 87, from: '中国', to: '四国', days: 1 },{ id: 88, from: '中国', to: '九州', days: 2 }, 
    { id: 89, from: '中国', to: '沖縄', days: 3 },
    { id: 90, from: '四国', to: '北海道', days: 3 },{ id: 91, from: '四国', to: '東北', days: 2 },
    { id: 92, from: '四国', to: '関東', days: 2 },{ id: 93, from: '四国', to: '甲信越', days: 2 },
    { id: 94, from: '四国', to: '北陸', days: 2 },{ id: 95, from: '四国', to: '東海', days: 1 }, 
    { id: 96, from: '四国', to: '近畿', days: 1 },{ id: 97, from: '四国', to: '中国', days: 1 }, 
    { id: 98, from: '四国', to: '四国', days: 1 },{ id: 99, from: '四国', to: '九州', days: 2 }, 
    { id: 100, from: '四国', to: '沖縄', days: 3 },
    { id: 101, from: '九州', to: '北海道', days: 3 },{ id: 102, from: '九州', to: '東北', days: 2 },
    { id: 103, from: '九州', to: '関東', days: 2 },{ id: 104, from: '九州', to: '甲信越', days: 2 },
    { id: 105, from: '九州', to: '北陸', days: 2 },{ id: 106, from: '九州', to: '東海', days: 2 }, 
    { id: 107, from: '九州', to: '近畿', days: 2 },{ id: 108, from: '九州', to: '中国', days: 1 }, 
    { id: 109, from: '九州', to: '四国', days: 2 },{ id: 110, from: '九州', to: '九州', days: 2 }, 
    { id: 111, from: '九州', to: '沖縄', days: 3 },
    { id: 112, from: '沖縄', to: '北海道', days: 3 },{ id: 113, from: '沖縄', to: '東北', days: 3 },
    { id: 114, from: '沖縄', to: '関東', days: 3 },{ id: 115, from: '沖縄', to: '甲信越', days: 3 },
    { id: 116, from: '沖縄', to: '北陸', days: 3 },{ id: 117, from: '沖縄', to: '東海', days: 3 }, 
    { id: 118, from: '沖縄', to: '近畿', days: 3 },{ id: 119, from: '沖縄', to: '中国', days: 3 }, 
    { id: 120, from: '沖縄', to: '四国', days: 3 },{ id: 121, from: '沖縄', to: '九州', days: 3 }, 
    { id: 122, from: '沖縄', to: '沖縄', days: 1 },
  ]
end